apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::431847813357:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-E5H10LKWM706
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::431847813357:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-19T23:01:59Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1872"
  uid: 988798e2-31df-478b-92a5-20e32706d618
